pool:
  vmImage: 'ubuntu-latest'
trigger:
  none

variables:
- name: one
  value: East US 
- name: two
  value: frank-test-sf-api-management-service.template.json
- name: three
  value: frank-test-sf-parameters.json 

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: moshidevopsconnection
    subscriptionId: 'a2d49d28-b5b1-48fe-83dc-ada50a035a99'
    resourceGroupName: moshidevopsconnection
    location: $(one)
    csmFile: $(two)
    csmParametersFile: $(three)
